#! stack runhaskell

{-
Uses the `etlas deps` command to retrieve the list of dependency jars for
Finally it reads the project.clj template and pastes the extracted jars as resources into the
project.clj template at the marker location and prepends a notice that the file is generated
-}

{-# LANGUAGE OverloadedStrings #-}

import           Control.Applicative
import           Control.Category    ((>>>))
import           Data.Function
import           Data.Maybe
import           Data.Monoid         ((<>))
import qualified Data.Text           as T
import qualified Data.Text.IO        as T
import           System.Process

depInsertMarker = "(- insert-jar-deps -)"
projectFile = "project.clj"
templatePrefix = "template."
templateFile = templatePrefix <> projectFile
notice = T.append "; " $ T.intercalate "\n; "
    [ "NOTICE This file is generated by GenProjectClj.hs."
    , "Do not modify this file as changes will be overwritten when the file is regenerated."
    , "Commit your changes to the " <> T.pack templateFile <> " file instead."
    , "Furthermore please make sure you do not remove or alter the insertion marker \"" <> depInsertMarker <> "\""
    , "in the template file."
    ]


main = do
    deps <- T.intercalate " "
            . map (\t -> '"' `T.cons` t `T.snoc` '"')
            . init
            . T.lines
            . T.pack
            <$> readCreateProcess (proc "etlas" ["deps", "--classpath", "lib:ohua-jvm-integration"]) ""
    template <- T.readFile templateFile
    T.writeFile projectFile $ T.intercalate deps (T.splitOn depInsertMarker template) `T.snoc` '\n' <> notice
